### ISSUE TITLE
Cannot run tgcli.exe on Win10 Home Chinese version 19042.1052

### ISSUE THREAD

**Issue by jiemingzhou-tigergraph** [TigerGraph-DevLabs/TigerGraph-CLI#1]
Reproduce Steps
1. Downloaded tgcli.exe from https://tigertool.tigergraph.com/dl/windows/tgcli.exe
2. Ran it on my computer, got an "Unknown Publisher" warning.
2. Continued to run, get an error "This app can’t run on your PC".
3. Tried to run it in the compatible mode in Win7/8, still got the same error.

My Windows is Win10 Home Chinese version 19042.1052. Can I have a runnable tgcli.exe on it?

**Comment by zrougamed** [comment]
Hi @jiemingzhou-tigergraph  

Thanks for reporting this issue we have reissued a new EXE  File and has been tested under 19043.1052 ( Shell in screenshot below )  , could you please check and confirm ? 

https://tigertool.tigergraph.com/dl/windows/tgcli.exe

Thanks !


![19043-1052](https://user-images.githubusercontent.com/61499067/124813066-55899f80-df5c-11eb-8489-f8fa82860fe8.PNG)

**Comment by jiemingzhou-tigergraph** [comment]
Thanks! I verified it works.
