### ISSUE TITLE
Signing in as a different user not possible after logging in

### ISSUE THREAD

**Issue by DanBarkus** [TigerGraph-DevLabs/TigerGraph-CLI#3]
On Mac, after you have logged in successfully, re-running `login` will default to the currently logged in user even if a separate username is supplied in the command.

**Comment by zrougamed** [comment]
when using 
```
tgcloud cloud login 
```
by default it gets what is in the configuration manager 

to specify a different account use 

```
tgcloud cloud login  -email <email> -password <password>
```

if email and password are not provided it will get the default conf tgcloud account 

@DanBarkus  could you please confirm that the switches work ?

**Comment by zrougamed** [comment]
Issue solved 
check update on 
https://github.com/TigerGraph-DevLabs/TigerGraph-CLI/issues/4
