### ISSUE TITLE
Unable to change tg cloud user credentials 

### ISSUE THREAD

**Issue by lennessyy** [TigerGraph-DevLabs/TigerGraph-CLI#4]
I logged in on a free account that's run out of credits and am trying to log into a new account

I ran:
```
tg conf tgcloud
What is your tgcloud user? lenny.chen@tigergraph.com
What is your tgcloud password? 
```
It would try my credentials for a while and then stop. I also tried logging in through `tg cloud login` and specify my username and password through flags, but I also can't seem to log in.

**Comment by zrougamed** [comment]
@lennessyy thanks for reporting this . Is this account SSO or normal user/pw login 

Please note that the cli doesn't support SSO yet .

**Comment by lennessyy** [comment]
I have tried both. 

I also heard from Jon yesterday that for SSO accounts on Cloud (Or just google specifically), the password is the Google password. I am able to log in on the TigerGraph cloud portal with user/pw login with my google password. 

I also tried logging in to another account of mine that's just username/password. For some reason I still can't log in.

**Comment by zrougamed** [comment]
That's interesting can you please specify the OS

**Comment by zrougamed** [comment]
@lennessyy  the issue is resolved Please check and confirm 

Thanks!

**Comment by lennessyy** [comment]
Can confirm issue is resolved. Thanks Mohamed!
