### ISSUE TITLE
GSQL command line not working on 3.3 ?

### ISSUE THREAD

**Issue by rik-tg** [TigerGraph-DevLabs/TigerGraph-CLI#7]
I got this. I'm portforwarding to an AWS box (via ssh) if that makes any difference : 

richardh@TigerGrQJE4MD6T next-generation % tg box gsql -host 127.0.0.1 
No connection adapters were found for '127.0.0.1:14240/gsqlserver/gsql/login'
No connection adapters were found for '127.0.0.1:14240/gsqlserver/gsql/login'

**Comment by zrougamed** [comment]
Hey Rik 

Thanks for reporting this , there is a pending update for the cli to support 3.2+ . So for now the actual version of the cli won't connect to your host.

The second point is that you omitted the http schema ( http:// )

**Comment by rik-tg** [comment]
I understand.

**Comment by zrougamed** [comment]
@rik-tg  tgcli is updated to 0.5.2 and added support to TigerGraph 3.2+
